"""
pipeline.py

Naive RAG Orchestrator for the Banking Copilot.
Coordinates retrieval from pgvector, prompt construction, and generation via Groq.
"""

from typing import List, Dict, Any, Optional

from src.logger import get_logger
from src.retrieval.vector_search import VectorSearcher
from src.generation.prompt import build_prompt
from src.generation.llm import GroqLLM

logger = get_logger(__name__)


class NaiveRAGPipeline:
    """
    End-to-End Naive RAG Pipeline:
    Question -> Semantic Retrieval -> Prompt Construction -> LLM Generation -> Grounded Answer
    """

    def __init__(
        self,
        searcher: Optional[VectorSearcher] = None,
        llm: Optional[GroqLLM] = None,
        top_k: int = 3
    ):
        """
        Args:
            searcher: VectorSearcher instance (defaults to a new one).
            llm: GroqLLM instance (defaults to a new one).
            top_k: Number of document chunks to retrieve per question.
        """
        self.searcher = searcher or VectorSearcher(top_k=top_k)
        self.llm = llm or GroqLLM()
        self.top_k = top_k
        logger.info(f"NaiveRAGPipeline initialized (top_k={self.top_k})")

    def ask(self, question: str, top_k: Optional[int] = None) -> Dict[str, Any]:
        """
        Answers a banking operations question using the RAG pipeline.

        Args:
            question: Natural language question from employee.
            top_k: Optional override for number of retrieved chunks.

        Returns:
            Dict containing:
            - 'question': Original user query
            - 'answer': Grounded answer generated by Groq
            - 'sources': List of unique document filenames used
            - 'chunks': Raw retrieved chunks with similarity scores
        """
        k = top_k or self.top_k
        logger.info(f"Processing question: '{question}' (top_k={k})")

        # 1. RETRIEVAL: Query pgvector for semantically relevant chunks
        chunks = self.searcher.search(question, top_k=k)

        if not chunks:
            logger.warning("No relevant chunks retrieved from database.")
            return {
                "question": question,
                "answer": "I do not have sufficient information in the banking documentation to answer this question.",
                "sources": [],
                "chunks": []
            }

        # Extract unique sources cited
        unique_sources = list(dict.fromkeys(c.get("source_file", "unknown") for c in chunks))

        # 2. PROMPT CONSTRUCTION: Format context + system prompt + query
        messages = build_prompt(question, chunks)

        # 3. GENERATION: Send formatted messages to Groq LPU
        raw_answer = self.llm.generate(messages)
        answer = raw_answer.replace("\r\n", "\n").replace("\r", "\n").strip()

        return {
            "question": question,
            "answer": answer,
            "sources": unique_sources,
            "chunks": chunks
        }

    def close(self):
        """Closes the vector searcher database connection."""
        if self.searcher:
            self.searcher.close()


if __name__ == "__main__":
    # Quick CLI test run
    rag = NaiveRAGPipeline(top_k=2)

    test_question = "What is the procedure to reverse a failed IMPS transaction?"
    print("\n" + "=" * 70)
    print(f"QUESTION: {test_question}")
    print("=" * 70)

    result = rag.ask(test_question)

    print("\nANSWER:")
    print(result["answer"])
    print("\n" + "-" * 70)
    print("SOURCES CITED:", ", ".join(result["sources"]))
    print("=" * 70 + "\n")

    rag.close()
